when:
  - event: cron
    cron: "daily"

steps:
  - name: Przygotowanie
    image: bash
    commands:
      - ln -s $${IMPORT_HELPER_PATH} ./import_helper
    secrets: [ IMPORT_HELPER_PATH ]

  - name: Dzienne aktualizacje
    image: bash
    commands:
      - bun src/marcupdates.ts > $${RAPORT_DZIENNY_IMPORT_PATH} 2>&1 && mv /var/tmp/raport_dzienny_import.txt $${RAPORT_DZIENNY_IMPORT_SHORT_PATH}
    secrets: [ RAPORT_DZIENNY_IMPORT_PATH, RAPORT_DZIENNY_IMPORT_SHORT_PATH ]