when:
  - event: cron
    cron: "daily"

steps:
  - name: Przygotowanie
    image: bash
    commands:
      - ln -s $${IMPORT_HELPER_PATH} ./import_helper
      - $${BUN_PATH} install --frozen-lockfile
    secrets: [ BUN_PATH, IMPORT_HELPER_PATH ]

  - name: Dzienne aktualizacje
    image: bash
    commands:
      - $${BUN_PATH} src/marcupdates.ts 2>&1 | tee $${RAPORT_DZIENNY_IMPORT_PATH}
      - mv /var/tmp/raport_dzienny_import.txt $${RAPORT_DZIENNY_IMPORT_SHORT_PATH}
    secrets: [ BUN_PATH, RAPORT_DZIENNY_IMPORT_PATH, RAPORT_DZIENNY_IMPORT_SHORT_PATH ]