when:
  - event: cron
    cron: "sobota"

steps:
  - name: Przygotowanie
    image: bash
    commands:
      - $${BUN_PATH} install --production --frozen-lockfile
    secrets: [ BUN_PATH ]

  - name: Sobota
    image: bash
    commands:
      - echo $${RAPORT_SOBOTA_PATH}
      - $${BUN_PATH} src/sobota.ts 2&>1 | tee $${RAPORT_SOBOTA_PATH}
    secrets: [ BUN_PATH, RAPORT_SOBOTA_PATH ]

  - name: Podsumowanie
    image: bash
    commands: |
      [ ! -f /var/tmp/raport_sobota.txt ] && echo "Brak raportu?"
      [ ! -f /var/tmp/raport_sobota.txt ] || ( mv /var/tmp/raport_sobota.txt $${RAPORT_SOBOTA_SHORT_PATH} && cat $${RAPORT_SOBOTA_SHORT_PATH} )
    secrets: [ RAPORT_SOBOTA_SHORT_PATH ]