when:
  - event: cron
    cron: "sobota"

steps:
  - image: bash
    commands:
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH=$BUN_INSTALL/bin:$PATH
      - bun src/sobota.ts > $${RAPORT_SOBOTA_PATH} 2>&1
    secrets: [ RAPORT_SOBOTA_PATH ]