when:
  - event: cron
    cron: "sobota"

steps:
  - name: Przygotowanie
    image: bash
    commands:
      - $${BUN_PATH} install --frozen-lockfile
    secrets: [ BUN_PATH ]

  - name: Sobota
    image: bash
    commands:
      - $${BUN_PATH} src/sobota.ts 2&>1 | tee $${RAPORT_SOBOTA_PATH}
    secrets: [ BUN_PATH, RAPORT_SOBOTA_PATH ]